version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    restart: always
    ports:
      - "1884:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - mqtt_network

networks:
  mqtt_network:
    driver: bridge
